version: '3'

services:
  db:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - 1433:1433
    volumes:
      - ./tmp:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=msSql_password
      - MSSQL_PID=Developer
