version: "3"

services:
  db:
    image: microsoft/mssql-server-linux
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=msSql_password
      - MSSQL_PID=Developer
